### PR TITLE
Fixed your README - you're welcome.

### PR DESCRIPTION
**Pull request by htbrown**

### CODE REVIEW

**Comment by XilogOfficial** [comment]
# no

**Comment by alecks** [comment]
open

**Comment by XilogOfficial** [comment]
no

**Comment by alecks** [comment]
haskell

**Comment by htbrown** [comment]
im offended

**Comment by XilogOfficial** [comment]
haskell and c# both cause brain damage go is easy and Cool

**Comment by alecks** [comment]
C# doesn't cause brain damage

haskell does

**Comment by XilogOfficial** [comment]
but c# is gay

**Pull request closed without merging**
